language: bash

sudo: required

services:
  - docker

stages:
  - compile
  - name: deploy
    if: branch = master

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.18.0
    - VARIANT=cli
    - VARIANT=fpm-base
    - VARIANT=fpm
    - VARIANT=nginx
    - VARIANT=build
  matrix:
    - MAJOR_VERSION=5.6 PHP_VERSION=5.6.34
    - MAJOR_VERSION=7.0 PHP_VERSION=7.0.28
    - MAJOR_VERSION=7.1 PHP_VERSION=7.1.15
    - MAJOR_VERSION=7.2 PHP_VERSION=7.2.3

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - env | sort
  - cd "$MAJOR_VERSION/$VARIANT"
  - image="xutongle/php:${MAJOR_VERSION}-${VARIANT}"

script:
  - travis_retry docker build --build-arg PHP_VERSION=${PHP_VERSION} -t "$image" .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login --username="${DOCKER_REGISTRY_USER}" --password="${DOCKER_REGISTRY_PASSWORD}";
      docker push $image;
      docker tag $image xutongle/php:${PHP_VERSION}-${VARIANT};
      docker push xutongle/php:${PHP_VERSION}-${VARIANT};
      if [ "${MAJOR_VERSION}" == "7.1" ]; then
        if [ "${VARIANT}" == "fpm" ]; then
          docker tag $image xutongle/php:latest;
          docker push xutongle/php:latest;
          docker tag $image xutongle/php:${PHP_VERSION};
          docker push xutongle/php:${PHP_VERSION};
          docker tag $image xutongle/php:${VERSION};
          docker push xutongle/php:${VERSION};
        fi
      fi
    fi

# vim:set et ts=2 sw=2:
